service:
  name: quik-provider
  standard-settings-controller:
    enabled: true
  simple-worker:
    enabled: true
    name: simple-worker
    wait-on-stop-ms: 1000
    wait-on-restart-ms: 20000
    min-time-per-iteration-ms: 1000
    timeout-runner-life-ms: 60000
    print-statistics-every-ms: 1000
  channels-api:
    quik-provider-snapshots:
      securities-v1.enabled: true
    quik-provider-streams:
      securities-v1.enabled: true
      orders-v1.enabled: true
      deals-v1.enabled: true
      all-trades-v1.enabled: true
  kafka:
    server: localhost:9092
    outcome-topics:
      standard-uploader.enabled: true
  redis:
    outcome-collections:
      standard-uploader.enabled: true


# Логирование
logging:
  level:
    org.springframework: info
    org.springframework.orm: info
    org.springframework.web: info

# Настройки Сервера
server:
  port: 7101

#quik
quik:
  connector.enabled: true
  pipe-name: C-QUIK_VTB-
  buffer-size: 32768
  attempts-on-connect: 20
  pause-on-connect-ms: 3000
  interval-mandatory-read-state-ms: 5000

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true