service:
  name: quik-provider
  simple-settings-controller:
    enabled: true
  simple-worker:
    enabled: true
    wait-on-stop-ms: 1000
    wait-on-restart-ms: 20000
    min-time-per-iteration-ms: 1000
    timeout-runner-life-ms: 60000
  outcome-topics:
    configurator-caller.enabled: true
    simple-configuration.enabled: true
    standard-uploader.enabled: true
    standard-offsets-controller.enabled: true

# Логирование
logging:
  level:
    org.springframework: info
    org.springframework.orm: info
    org.springframework.web: info

# Настройки Сервера
server:
  port: 7001

#quik
quik:
  connector.enabled: true
  pipe-name: C-QUIK_VTB-
  buffer-size: 32768
  attempts-on-connect: 20
  pause-on-connect-ms: 3000
  interval-mandatory-read-state-ms: 5000

#kafka
kafka:
  server: localhost:9092
  outcome-topics:
    all-trades: quikProviderAllTrades
    deals: quikProviderDeals
    orders: quikProviderOrders
    securities: quikProviderSecurities

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false